const teori1 = [
    {koreansk: 'Charyôt', norsk: 'Giv akt stilling'},
    {koreansk: 'Baro / Goman', norsk: 'Stopp'},
    {koreansk: 'Kyôngnye', norsk: 'Hilse'},
    {koreansk: 'Gihap (Ki-ap)', norsk: 'Skrik (Ki = Energi, Ap = Samle)'},
    {koreansk: 'Junbi', norsk: 'Start stilling'},
    {koreansk: 'Dwirodora', norsk: 'Snu'},
    {koreansk: 'Ap chagi', norsk: 'Frontspark med vrist'},
    {koreansk: 'Dollyo chagi',norsk: 'Rundspark'},
    {koreansk: 'Yop chagi',norsk: 'Sidespark'},
    {koreansk: 'Dojang', norsk: 'Treningssal'},
    {koreansk: 'Dobok', norsk: 'Taekwondo drakt'},
    {koreansk: 'Sabõm-nim', norsk: 'Master'},
    {koreansk: 'Gyosa-nim', norsk: 'Instruktør'},
    {koreansk: 'Chigi', norsk: 'Slag/støt (der armen går i en sirkelbevegelse)'},
    {koreansk: 'Jireugi', norsk: 'Slag (der armen går i en strak linje)'},
    {koreansk: 'Kobi', norsk: 'Felles betegnelse for lange stillinger'},
    {koreansk: 'Seogi', norsk: 'Felles betegnelse for korte stillinger'},
    {koreansk: 'Makki', norsk: 'Blokk'},
    {koreansk: 'Apchok ap chagi', norsk: 'Frontspark med tåball'},
    {koreansk: 'An chagi',norsk: 'Innadgående spark'},
    {koreansk: 'Bakkat chagi',norsk: 'Utadgående spark'},
    {koreansk: 'Olgul', norsk: 'Fra kravebenet og opp'},
    {koreansk: 'Momtong', norsk: 'Fra kravebenet ned til hoftebeinet '},
    {koreansk: 'Area', norsk: 'Fra hoftebeinet og ned'},
    {koreansk: 'Mit chagi', norsk: 'Skrått spark (ca. 45°)'},
    {koreansk: 'Mira chagi', norsk: 'Dyttespark'},
    {koreansk: 'Mori', norsk: 'Hode'},
    {koreansk: 'Mok', norsk: 'Hals'},
    {koreansk: 'Mom', norsk: 'Kroppen'},
    {koreansk: 'Jumeok', norsk: 'Knytteneve'},
    {koreansk: 'Deongjumeok', norsk: 'Håndbak'},
    {koreansk: 'NKF', norsk: 'Norsk kampsport forbund'},
    {koreansk: 'WTF', norsk: 'World Taekwondo Federation'},
    {koreansk: 'Kukkiwon', norsk: 'WTFs hovedkvarter i Seoul, Sør-Korea'},
    {koreansk: 'Bandae yop chagi', norsk: 'Baklengs sidespark (med rotasjon)'},
    {koreansk: 'Naeryo chagi', norsk: 'Frontspark med kraft nedover'},
    {koreansk: 'Kyoregi', norsk: 'Frikamp'},
    {koreansk: 'Hana', norsk: '1'},
    {koreansk: 'Dul', norsk: '2'},
    {koreansk: 'Set', norsk: '3'},
    {koreansk: 'Net', norsk: '4'},
    {koreansk: 'Daseot', norsk: '5'},
    {koreansk: 'Yaseot', norsk: '6'},
    {koreansk: 'Ilgop', norsk: '7'},
    {koreansk: 'Yadul', norsk: '8'},
    {koreansk: 'Ahop', norsk: '9'},
    {koreansk: 'Yeol', norsk: '10'},
    {koreansk: 'Pal', norsk: 'Arm (fra skulder til håndledd)'},
    {koreansk: 'Dari', norsk: 'Ben (fra hofteben til ankel)'},
    {koreansk: 'Batangson', norsk: 'Nederste del av håndflate'},
    {koreansk: 'Son', norsk: 'Hånd (fra håndleddet og ut) '},
    {koreansk: 'Bal', norsk: 'Fot (fra ankelen og ned) '},
    {koreansk: 'Bandae dollyo chagi ', norsk: 'Hookspark'},
    {koreansk: 'Twio ap chagi', norsk: 'Hoppende frontspark'},
];
const teori2 = [
    {koreansk: 'Gyokpa', norsk: 'Brekking'},
    {koreansk: 'Chong', norsk: 'Blå'},
    {koreansk: 'Hong', norsk: 'Rød'},
    {koreansk: 'Palkup', norsk: 'Albue'},
    {koreansk: 'Palmok', norsk: 'Håndledd'},
    {koreansk: 'Sonnal', norsk: 'Lillefingeresiden av en åpen hånd (knivhånd)'},
    {koreansk: 'Deongsonnal', norsk: 'Tommelfingersiden av en åpen hånd'},
    {koreansk: 'Jabki', norsk: 'Grep'},
    {koreansk: 'Mureup', norsk: 'Kne'},
    {koreansk: 'Momdollyo chagi', norsk: 'Roterende frontspark (spinnkick)'},
    {koreansk: 'Twio yop chagi', norsk: 'Hoppende sidespark (flykick)'},
    {koreansk: 'Dwit chagi ', norsk: 'Bakspark'},
    {koreansk: 'Dolyo chagi', norsk: 'Rundspark'},
    {koreansk: 'Momtong jireugi', norsk: 'Rett slag'},
    {koreansk: 'Kukki', norsk: 'Flagg'},
    {koreansk: 'Tae', norsk: 'Fot'},
    {koreansk: 'Kwon', norsk: 'Hånd'},
    {koreansk: 'Do', norsk: 'Kunst/vei'},
    {koreansk: 'Teok', norsk: 'Kjeve'},
    {koreansk: 'Tae Kyon', norsk: 'Opphavet til dagens taekwondo'},
    {koreansk: 'Il', norsk: 'Første'},
    {koreansk: 'I', norsk: 'Andre'},
    {koreansk: 'Sam', norsk: 'Tredje'},
    {koreansk: 'Sah', norsk: 'Fjerde'},
    {koreansk: 'Oh', norsk: 'Femte'},
    {koreansk: 'Yuk', norsk: 'Sjette'},
    {koreansk: 'Chil', norsk: 'Syvende'},
    {koreansk: 'Pal', norsk: 'Åttende'},
    {koreansk: 'Ko', norsk: 'Niende'},
    {koreansk: 'Sip', norsk: 'Tiende'},
    {koreansk: 'Dwidola bandae dollyo chagi', norsk: 'Roterende hookspark'},
    {koreansk: 'Twio dollyo chagi', norsk: 'Hoppende rundspark'},
    {koreansk: 'Dwidola bansdae dollyo chagi', norsk: 'Roterende hookspark'},
    {koreansk: 'Twio yop chagi', norsk: 'Hoppende sidespark'},
    {koreansk: 'Sonnal bakkat chigi', norsk: 'Knivhåndslag utover'},
];
const teori3 = [
    {koreansk: 'Hosinsul', norsk: 'Selvforsvar'},
    {koreansk: 'Apchuk', norsk: 'Tåball'},
    {koreansk: 'Dwitchuk', norsk: 'Hæl'},
    {koreansk: 'Dwikkumchi', norsk: ' Baksiden av hælen'},
    {koreansk: 'Baldeung', norsk: 'Vrist'},
    {koreansk: 'Balnal', norsk: 'Knivseggen på foten'},
    {koreansk: 'Wen', norsk: 'Venstre'},
    {koreansk: 'Oreun', norsk: 'Høyre'},
    {koreansk: 'Taegukki', norsk: 'Navnet på det koreanske flagget'},
    {koreansk: 'Bitureo chagi', norsk: 'Omvendt mit chagi utover'},
    {koreansk: 'Mureup chagi', norsk: 'Knespark'},
];
